### ISSUE TITLE
Error upon build test: "Failed to execute goal..."

### ISSUE THREAD

**Issue by zakdances** [mttkay/ignition#5]
I am running Windows 7 with Android SDK v. 4.0.3 (API 15).

Failed to execute goal com.jayway.maven.plugins.android.generation2:android-maven-plugin:3.0.2:generation-sources (default-generate-sources) on project ignition-core: Execution default-generate-sources of goal com.jayway.maven.plugins.android.generation2:android-maven-plugin:3.0.2:generate-sources failed: Invalid SDK: Platform/API level 4 not available.
 This command should give you all you need:
C:/Program Files (x86)\Android\android-sdk\tools\android update sdk --no-ui --obsolete --force

Why do you I need to install obsolete version of the Android SDK just to get ignition to work?

**Comment by mttkay** [comment]
Are you sure you're building against the latest master? We've removed all references to the maven-sdk-deployer artifact, so that should work now. Do a gut pull and try again.

As for the "obsolete" remark, 1.6 is not obsolete as in deprecated/unsupported; only 1.5 is. We always build the library against the smallest set of Android APIs that we need, which as of now is 1.6. This makes sure that the library will work for everyone from 1.6 to 4.0.

**Comment by mttkay** [comment]
ignition now depends on the Android JARs from Central, so this should be fixed.
